/* Server version: WI-V6.3.7.27050 Firebird 2.5 
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 16384. Cache pages: 2048 (32768 Kb). Read-only: False. */
SET NAMES ISO8859_1;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Create Domains... */
CREATE DOMAIN DM_DATA AS DATE;

CREATE DOMAIN DM_DESCRICAO AS VARCHAR(100);

CREATE DOMAIN DM_ID AS INTEGER;

CREATE DOMAIN DM_NUMERO AS INTEGER;

CREATE DOMAIN DM_QUANT AS DOUBLE PRECISION;

CREATE DOMAIN DM_VALOR AS DOUBLE PRECISION;

/* Create Table... */
CREATE TABLE ITEM(ID_ITEM DM_ID NOT NULL,
DESC_ITEM DM_DESCRICAO);


CREATE TABLE PEDIDOCAB(ID_PED DM_ID NOT NULL,
DTEMISSAO DM_DATA,
NUMERO DM_NUMERO,
CLIENTE DM_DESCRICAO);


CREATE TABLE PEDIDOITEM(ID_PED DM_ID NOT NULL,
ID_ITEM DM_ID NOT NULL,
ID_ITEMSEQ DM_ID NOT NULL,
QUANTIDADE DM_QUANT,
VALORUNIT DM_VALOR,
VALORTOTAL DM_VALOR);


/* Create generator... */
CREATE GENERATOR GEN_ITEM;

CREATE GENERATOR GEN_PEDIDO;


/* Create Primary Key... */
ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ID_ITEM);

ALTER TABLE PEDIDOCAB ADD CONSTRAINT PK_PEDIDOCAB PRIMARY KEY (ID_PED);

ALTER TABLE PEDIDOITEM ADD CONSTRAINT PK_TABLE3 PRIMARY KEY (ID_PED, ID_ITEM, ID_ITEMSEQ);

/* Create Foreign Key... */
RECONNECT;

ALTER TABLE PEDIDOITEM ADD CONSTRAINT FK_ITEM FOREIGN KEY (ID_ITEM) REFERENCES ITEM (ID_ITEM);

ALTER TABLE PEDIDOITEM ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PED) REFERENCES PEDIDOCAB (ID_PED) ON DELETE CASCADE;

